security:
    providers:
        our_db_provider:
            entity:
                class: App\Entity\Participant
                property: username
    firewalls:
        main:
            pattern: ^/
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            #logout_on_user_change: true
            logout:
                path: logout
                target: home
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 #une semaine en secondes !
                path: /

    encoders:
       App\Entity\Participant:
            algorithm: bcrypt