#index:
#    path: /
#    controller: App\Controller\DefaultController::index

ajax_ville:
  path: /ajax/selectVille
  defaults: { _controller: 'App\Controller\SortieController::selectVille' }
  requirements:
    _method: GET

ajax_lieu:
  path: /ajax/selectLieu
  defaults: { _controller: 'App\Controller\SortieController::selectLieu' }
  requirements:
    _method: GET